#Spartan Conquest
print("In this game you will be asked to make decisions and you will have to type some answers.")
print("You cannot go back and redo your decision unless you redo the whole game.")
print("If it doesn't ask you to answer something just press enter.")
enjoy = input("We hope you enjoy the game")
print("#" * int(20))
print("  SPARTAN CONQUEST          ")
begin = input("#" * int(20))
health = int(5)
honor = int(0)
battles = int(0)
name = input("What is your name??? ")
print(f"\"Welcome to the Spartan camp {name}. You have been training for months,")
print("and now the Persians are closing in and will take over If we stand still.")
prepare = input("You must prepare!\"")
choice1 = input("If you want to know more about the Persians go talk to King Leonidas, press L. If you want your weapon go to queen Gorgo, press W ")
choice11 = ((choice1). strip(). lower())
if (choice11) == "w":
    greets = input("You walk to queen Gorgo and she greets you with a smile.")
    print("Gorgo: \"Need a weapon young warrior? Do you want a sword or spear?\"")
    x = input("Type Sw for a sword or Sp for a spear ")
    w = ((x). strip(). lower())
    if w == "sw":
        print("Gorgo: \"Excellent choice\"")
        weapon = ("sword")
    elif w == "sp":
        print("Gorgo: \"you look like you're strong with a spear\"")
        weapon = ("spear")
    else:
        print("Gorgo: You going to pick one?")
elif (choice11) == "l":
    walk_over = input("You walk over to the king.")
    print("Leonidas: \"So you want to know more about the persians?")
    print("Well they are a kingdom beyond ours and ten times bigger than ours.")
    print("They are marching straight towards us and want to conquer us.")
    happen = input("But we won't let that happen.")
    happy_to_help = input("You should get a weapon, my wife will be happy to help.\"")
    smile = input("You walk to queen Gorgo and she greets you with a smile.")
    print("Gorgo: \"Need a weapon young warrior? Do you want a sword or spear?\"")
    x = input("Type Sw for a sword or Sp for a spear ")
    w = ((x). strip(). lower())
    if w == "sw":
        print("Gorgo: \"Excellent choice\"")
        weapon = ("sword")
    elif w == "sp":
        print("Gorgo: \"you look like you're strong with a spear\"")
        weapon = ("spear")
    else:
        print("\"Gorgo: You going to pick one?\"")
else:
    print("If you don't make a decision you can't continue")
print("A horn is blown and men come filing out of their tents.")
time_for_training = input("Time for training.")
print("If you want to attack press 'A'")
print("If you want to dodge press 'D'")
print("If you want to form a phalanx, press 'PPPP'")
lets_go = input("General: \"Ready to fight? Let's go!\"")
print("\"Attack\"")
a = input("Press A, D, or PPPP quickly ")
print("\"Excellent! Now Dodge!\"")
d = input("Press A, D, or PPPP quickly ")
print("\"Perfect timing now watch out when surrounded.")
print("Form Phalanx!\"")
p = input("Press A, D, or PPPP quickly ")
print("\"Nicely done now, ATTACK ATTACK ATTACK!!!\"")
aaa = input("Attack three times ")
dawn = input("\"Well done young warrior, rest now for we leave at dawn.\"")
battles = (int(battles) + int(1))
print("The sunrises faster than it could set, at least that's what it felt like.")
leave_tent = input(f"you get ready and grab your {weapon} then once you leave your tent, ")
print("your childhood friend Callista is standing outside.")
yes = input(f"Callista: \"Hey {name}, you ready?\" (yes/no)")
print("Callista: \"Well you'll do great.\"")
warms_heart = input("her smile warms your heart")
print("General: \"SOLDIERS today we head for the hot gates of Thermopylea!")
print("We will fight with honor and not guarentee of survival.")
made_of = input("TODAY WE SHOW THESE PERSIANS WHAT SPARTANS ARE MADE OF!!!\"")
cheer = input("Enter your cheer: ")
print("Soldiers: \"FOR SPARTA!\"")
yay = input(f"{name}: \"{cheer}!!!\"")
print("A thought comes to your mind.")
cal = input("Should I go say goodbye to Callista? (yes/no)")
b = ((cal). strip(). lower())
if (b) == "yes":
    print("you run over to Callista.")
    in_case = input(f"{name}: \"Goodbye Callista, in case I don't return.\"")
    kiss = input("A tear runs down her cheek. She steps forward and kisses you.")
    print("Callista: \"Here, take my blessing. It might come in handy.\"")
    print("Power Unlocked: Callista's Blessing")
    print("You wonder how this might help you.")
    callistas_blessing = True
elif (b) == "no":
    print("You stand up straight and prepare to leave.")
    callistas_blessing = False
#part2
print("You and your flank march towards the gates of Thermopylea ready to fight.")
real_battle = input("This is your first real battle... and it might be your last.")
review = input("You review your tactics.")
print("\"A\" is attack")
print("\"D\" is dodge")
you_ready = input("\"PPPP\" is form phalanx. You feel ready.")
print("As quick as lightning a pack of wolves jump out and attack your flank. One wolf jumps at you.")
fight = input("You, A, D, or PPPP ")
f = ((fight). strip(). lower())
if (f) == "a":
    print(f"You thrust your {weapon}, and you kill the wolf.")
elif (f) == "d":
    print("You duck and the wolf goes over your head, and another Spartan slashes it with his sword.")
elif (f) == "pppp":
    print(f"{name}: \"FORM A PHALANX!\" Your Flank locks their shields together and the wolves can't attack")
wolves_retreat = input("Your Flank does well and the wolves run away.")
battles = (int(battles) + int(1))
victory_dance = input("You guys do your victory dance until you notice the other Flanks aren't there.")
print(f"{name}: \"Where are the other Flanks?\"")
print("Soldier: \"They must have gone on while we were fighting the wolves.\"")
print(f"{name}: \"Did they go right or left?\"")
print("you all stare at the fork in the road. Which way did they go.")
print(f"Soldier: \"Which way do you think they went {name}?\"")
path = input("Which way do you think they went? press l for left and r for right")
direction = ((path). strip(). lower())
if (direction) == "l":
    left = input("The flank marches down the left path hoping they would find the other flanks and support them in the upcoming battle.")
    print("As you march you see this mysterious man sitting on a rock.")
    print(f"You draw you {weapon}.")
    print("Soldier: \"Are you friend or foe?\"")
    foe = input("Creepy man: \"Niether friend nor foe")
    challenge = input("But a challenge to go")
    pick_chest = input("Pick a chest and a prize will ring")
    honor_nothing = input("Gain honor or nothing.\"")
    chest = input("Do you open chest A, chest B or chest C?")
    chests = ((chest). strip(). lower())
    if (chests) == "a":
        print("You gained 3 honor")
        print("With this much honor maybe you will rank higher!")
        honor = (int(honor) + int(3))
    elif (chests) == "b":
        print("You gained nothing")
        print("What a shame")
    elif (chests) == "c":
        print("You gained health 2+")
        print("With this much health the Persians will never win!")
        health = (int(health) + int(2))
    soon = input("Your flank keeps moving forward since you need to get to the gates of Thermopylae soon.")
    silent_hills = input("The hills are silent as if they are waiting.")
    print("Like a waterfall a banned of Persians flow out from a corner.")
    ambush = input(f"{name}: AMBUSH!!!")
    shepherd = False
    print("A soldier comes and knocks you down before you could fight. Everything goes black.")
    lose_health = input("- 1 health")
    battles = (int(battles) + int(1))
    health = (int(health) - int(1))
    print("You wake up and there is no one around and there is an arrow in your arm.")
    print("you rip it out and rip a piece of your clothes to make a bandage.")
    keep_going = input("You need to keep going.")

elif (direction) == "r":
    right = input("The flank marches down the right path hoping they would find the other flanks and support them in the upcoming battle.")
    help = input("As you marched you hear a boys voice calling for help.")
    holding_lamb = input("You run up and see a shepherd boy stuck in a big bush of thistles and holding a lamb.")
    print("Boy: \"Can you please help me out?\"")
    choices = input("You look ahead and you see the other flanks under attack.")
    print("They need your help but so does this boy.")
    s = input("Press b to help the boy, press f to save the other flanks")
    sh = ((s). strip(). lower())
    if (sh) == "b":
        im_coming = input(f"{name}: \"Don't worry I'm coming.\" (You turn to your flank) \"Go and help the others, I'll be right behind you.\"")
        print("You climb into the thistles and they scratch at your skin.")
        alone = input("Your flank leaves and you realize you are now alone.")
        hooray = input("You use your shield to whack at the thistles making a path for the boy to walk through.")
        print("You, the boy, and the lamb make it out of the thistles but you are covered in cuts and blood.")
        print("- 1 health 1+ honor")
        health = (int(health) - int(1))
        honor = (int(honor) + int(1))
        wandering_hills = input("Boy: \"THANKS SO MUCH! By the way do you know that there are big scary men that say they are from some place called Persia wandering these hills?\"")
        print(f"{name}: \"WHAT?!? The Persians must have arrived earlier than expected.\"")
        print("Boy: \"Well I showed them a path that goes around the gates of Thermopylea.")
        avoid_gates = input("They said they wanted to avoid the gates.\"")
        print(f"{name}: \"They're going behind! THEY'RE GOING TO AMBUSH US!!!!\"")
        shepherd = True
    elif (sh) == "f":
        print("You and your flank ignore the boy and run towards the other flanks.")
        print("Once you arrive, the battle is over and half the men are dead.")
        print("There is one man still breathing.")
        print("You run over and fix up his wound.")
        gain_honor = input("1+ honor")
        honor = (int(honor) + int(1))
        print(f"{name}: \"Where did the others go?\"")
        hills_are_silent = input("The hills are silent as if they are waiting.")
        saw_you_coming = input(f"Soldier: \"{name} I think they saw us coming.\"")
        print("Like a waterfall a banned of Persians flow out from a corner.")
        print(f"{name}: \"AMBUSH!!!\"")
        shepherd = False
        print("A soldier comes and knocks you down before you could fight. Everything goes black.")
        print("You wake up and there is no one around and there is an arrow in your arm.")
        print("-2 health")
        health = (int(health) - int(2))
        battles = (int(battles) + int(1))
        print("you rip it out and rip a piece of your clothes to make a bandage.")
        print("You need to keep going.")
if shepherd == True:
    print("You run after your flank.")
    must_know = input("They must know about the Persians of they will all be ambushed!")
    print("You see your flank and the other flanks.")
    even_better = input("Even better you see King Leonidas.")
    print(f"{name}: \"Your majesty the Persians have arrived earlier than inticipated.")
    print("And they're not going through the gates of Thermopylae.")
    around = input("They're going around.")
    ambush_us = input("AND THEY'RE GOING TO AMBUSH US!\"")
    print("The king's eyes go wide.")
    turns_to_you = input("He thinks for a minute. Then turns to you.")
    print(f"King Leonidas: \"{name} will you lead the march to Thermopylae?")
    protect = input("We must protect Sparta and Athens the best we can.\"")
    front_of_flanks = input("You nod and take your place at the front of all the flanks.")
    print("To march you have to press the buttons in the right sequence to do the Spartan march.")
    go = input("Ready? Go!")
    march1 = input("L P W T ")
    print("Nicely done keep going!")
    march2 = input("H T D B A ")
    print("Great job!")
    march3 = input("3 7 5 1 ")
    print("King leonidas: \"Almost there I can see the gates\"")
    march4 = input("F O R S P A R T A !")
    print("You have arrived at the hot gates of Thermopylae.")
else:
    print("You see the gates of Thermopylae up ahead.")
    join_flanks = input("You run as fast as you can and quickly join your flank.")
    print("It's time for war!")
#part3
hades = input("King Leonidas: \"Men, eat now for tonight we dine in Hades!\"")
whats_next = input("You all cheer for it's better than thinking about whats next.")
print("You think of all your decisions leading up to this moment.")
regret = input("Which ones do you regret? What were your best?")
thunder = input("You pick up your drink and hear thunder in the distance.")
print("The thing is it wasn't thunder...It was the Persians.")
if shepherd == True:
    print("You get into position and you prepare for the battle of your life.")
else:
    print("You look ahead to prepare to fight.")
    print("Except they come from behind you")
    print("You are unprepared")
    come_from = input(f"{name}: \"WHERE DID THEY COME FROM!?!?\"")
    print("King Leonidas: \"IT'S AN AMBUSH!!!!!!!!!!\"")
    print("The Persians run at you and your unprepared flank.")
    print(f"You get trampled by a horse and you look for your {weapon}")
    print("- 1 health")
    health = (int(health) - int(1))
print("The battle has begun.")
battles = (int(battles) + int(1))
attack1 = input("What is your first attack? A D or PPPP? ")
at1 = ((attack1). strip(). lower())
if at1 == "a":
    print(f"You swing your {weapon} and take out the first guy.")
elif at1 == "d":
    print("You dodge the swings of three Persians and a smile grows on your face.")
elif at1 == "pppp":
    print(f"{name}: \"FORM A PHALANX!\"")
    print("You and your flank lock your shields together and push back a couple Persians.")
smooth = input("The battle goes somewhat smooth.")
more = input("But more Persians come and you are overwhelmed.")
print("A Persian charges at you.")
attack2 = input("What do you do? A D PPPP")
at2 = ((attack2). strip(). lower())
if at2 == "a":
    print(f"You raise your {weapon} and launch yourself at the charging Persian.")
    overtake = input("Your weapons clash and you can feel his strength start to overtake you.")
    duel1 = input("How many times will you swing your sword? Press a as much as you feel.")
    print("The Persian faulters back at your multiple attacks.")
elif at2 == "d":
    print("You try to dodge but you slam into a horse and the charging Persian slashes his sword through your back.")
    print("- 1 health")
    health = (int(health) - int(1))
elif at2 == "pppp":
    print(f"{name}: \"FORM A PHALANX!\"")
    no_response = input("No one responds to your call because everyone is overwhelmed.")
    print("The charging Persian thrusts his sword into your stomach.")
    print("- 1 health")
    health = (int(health) - int(1))
keep_going = input("You keep going not wanting to give up even as all your cuts started hurting.")
soldier_coming = input("A soldier comes up to you.")
print("Soldier: \"The king is overwhelmed, we must help him.\"")
print(f"{name}: \"There's too many our simple attacks won't work!\"")
print("Soldier: \"A ground smash should do the trick but you need to be strong enough.\"")
passage = input("Your health must be greater than two, a blessing would also work")
print(f"Health = {health}")
if health > int(2) or callistas_blessing:
    print(f"{name}: \"Let's do this\"")
    print("You and the soldier run towards the king.")
    if callistas_blessing == True:
        print("You feel Callista's blessing power you up.")
    elif callistas_blessing == False:
        pounding = input("Your feet pound hard against the dirt.")
    print("The soldier picks you up and throws you over the heads of the Persians.")
    ground_smash = input("Type smash to ground smash.")
    gs = True
    smashing = input(f"You raise you your {weapon} high in the air and you land right in the middle.")
    print("The gound shakes and the Persians fall backwards.")
    print("King Leonidas: \"Well done soldier that earns you 3+ honor.\"")
    print("3+ honor")
    honor = (int(honor) + int(3))
else:
    print(f"{name}: \"Time for a new plan.\"")
    gs = False
    new_plan = input("You and the soldier run at the persians surronding the king.")
    print(f"Soldier: \"{name}! Try a different attack like a slash or a thrust!\"")
    new = input("Type s for slash or T for thrust.")
    attacking = ((new). strip(). lower())
    if attacking == "s":
        print(f"You slash your {weapon} and take out three Persians.")
        print("King Leonidas: \"Well done soldier! you earned yourself 1+ honor!\"")
        print("1+ honor")
        honor = (int(honor) + int(1))
    elif attacking == "t":
        print(f"You thrust your {weapon} and take out a Persian that was about to cut the king in half.")
        print("King Leonidas: \"Well done soldier! You earned yourself 1+ honor.\"")
        next = input("1+ honor")
        honor = (int(honor) + int(1))
side = input("You and the king fight side by side holding back the Persians.")
print(f"King Leonidas: \"{name}! With you by my side we might see victory.\"")
mountian_flood = input("You really wish those words were true but you watch as more Persians flood from around the mountain.")
print(f"You hold up {weapon} ready to fight, there is no giving up.")
mutter = input("You hear the King mutter some words under his breath.")
shield = input("\"Come back with your shield or on it.\"")
print("King Leonidas: \"FOR SPARTA!!!!!\"")
battle_cry = input("Enter your battle cry: ")
print("Soldiers: \"FOR SPARTA!!!!\"")
print(f"{name}: \"{battle_cry}!!!!\"")
corpse = input("You run up beside your king but trip over a corpse.")
dead = input("You look up right as your king gets stabbed and falls to the ground dead.")
print(f"{name}: \"NOOOOOO!!!!!\"")
knocked_out = input("You run after your fallen king only to be knocked out by a Persian shield")
print("Then the lights go out.")
#part4
print("The world was dark and you feel like you're dead.")
print("Your heart beats ba dump... ba dump... ba dump.")
w = input("Wake yourself up, press any button: ")
a = input("Keep trying: ")
k = input("Still dark: ")
e = input("You hear humming, keep trying to wake up!: ")
while True:
    wake = input("Type the right number to wake up completely: ")
    if wake == "1":
        break
print("You shoot your eyes open and see Callista tending to your wounds.")
print(f"Callista: \"{name}! You're alive!\"")
gods = input("Gorgo: \"Thank the Gods!\"")
print(f"{name}: \"WHAT!?! WHERE!?! how did you guys find me?\"")
print("Callista: \"The queen was looking for her husband.\"")
sorry = input(f"{name}: \"I'm so sorry your majesty.\"")
print("Gorgo: \"No need for an apology, you are the only man that survived that battle.")
will_not_win = input("The Persians may have won that battle but they won't win the war.\"")
print("Callista helps you up and guides you to the edge of the cliff.")
advancing = input("You see the Persians advacing towards Athens and Sparta.")
print("Gorgo: \"so how do you feel young warrior?\"")
yet = input(f"{name}: \"The battle isn't over yet.\"")
print("Thus concludes Spartan Conquest")
stat = input("If you would like to see your stats click s, if you want to go stright to credits click c: ")
stats = ((stat). strip(). lower())
if stats == "s":
    print(f"{name}")
    print(f"Weapon = {weapon}")
    print(f"Honor = {honor}")
    print(f"Heath = {health}")
    print(f"Battles = {battles}")
    print("Earned Titles:")
    if callistas_blessing:
        print("Favourite Friend")
    if int(health) > int(3):
        print("Staying Alive")
    if int(honor) >= int(5):
        print("Honorable Soldier")
    if weapon == "sword":
        print("Swaggling Swords Men")
    if weapon == "spear":
        print("Pokey Spears Men")
    if gs == True:
        print("Ground Smasher")
    if int(health) <= int(2):
        print("Not Dead Yet")
ranking_health = input("Enter your number of health: ")
ranking_honor = input("Enter your honor: ")
try:
    print(f"You ranked {int(ranking_health) + int(ranking_honor)} Overall.")
    print("Gorgo: \"Not bad young warrior.\"")
except:
    print("You have to enter an integer.")
print("Credits:")
print("Designer: Abby Pilkey")
print("Layout: Abby Pilkey")
print("Special Shoutouts: Mr Tomas the robotics teacher, Mr Pickett the history teacher")
print("Gorgo: \"Thanks for playing young warrior\"")
#The End
